# Generated by Django 5.2.5 on 2025-09-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoucoureEnglishAcademy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cour', 'verbose_name_plural': 'Cours'},
        ),
    ]
